### ISSUE TITLE
docx.img hangs on docx.render

### ISSUE THREAD

**Issue by spiffistan** [trade-informatics/caracal#11] opened 2015-06-08 12:09 UTC
I'm using the following code:
```
docx.img image_url('logo-256.png'), width: 256, height: 256
```
Which according to byebug causes docx.render to hang infinitely. I've tried with several URLs and multiple settings.

Caracal 0.3.0, Caracal-rails 0.2.0, Ruby 2.2.2, Rails 4.2.1.

Any ideas?

EDIT: Confirmed to hang on Ruby 2.1.4 as well

**Comment by jdugan-plia** [comment] 2015-06-08 14:34
I'm going to be away from my computer for a few days so I'm working from memory here, but I suspect the issue is you need to provide a fully qualified path--either url or file path.

**Comment by spiffistan** [comment] 2015-06-08 18:49
I tested again with both a full path and a complete URL, both failed.

**Comment by jdugan-plia** [comment] 2015-06-16 14:50
I'm back from my trip.  I've always been able to render images just fine in all my environments, but I'll try to recreate using the exactly library versions you specified.

**Comment by jdugan-plia** [comment] 2015-06-16 18:24
There's nothing wrong with your stack.  These library versions work perfectly with my test application.  So, that's good.

My guess is you're only running one worker in development mode.  In that scenario, you send one request to generate the document, and in the process, it tries to send another to the server to read the image file.  But that second call can never complete because it gets blocked by the parent call to render the document.  Does that make sense?

To get around this, just use unicorn in development and configure it to have more than one worker.

**Comment by spiffistan** [comment] 2015-06-16 20:11
That does make sense, I'll try to switch to unicorn in dev tomorrow, thanks.

**Comment by spiffistan** [comment] 2015-06-16 20:40
It worked in puma with multiple workers. 

image_url('logo.png') did however GET /images/logo.png, whereas image_url('http://google.com/logo.png') resulted in GET /images/http://google.com/logo.png

Not sure if this is intended behaviour...

Is there any way to use the asset paths?

**Comment by jdugan-plia** [comment] 2015-06-16 20:54
Good.

`image_url` has nothing to do with Caracal.  That's a Rails helper.  Caracal accepts whatever string you pass into it.  When I do:

```ruby
image_url('logo.png')
``` 
I get:

```
http://localhost:3000/assets/logo.png
```

You might need to check your Rails config.  If `image_url` is giving an unexpected result, that's a Rails concern. 

I'm going to close this issue since switching to Puma solved the original issue.

**Closed by jdugan-plia** 2015-06-16 20:54 UTC

**Comment by spiffistan** [comment] 2015-06-16 21:16
Thanks. Great work with this gem by the way. It is sorely needed.
