### ISSUE TITLE
Crashes on JRuby 9.1.8.0 with NAMESPACE_ERR

### ISSUE THREAD

**Issue by jandillmann** [trade-informatics/caracal#61] opened 2017-04-21 10:31 UTC
I tried to get the example project to run on JRuby 9.1.8.0 with Rails 4.2.8, but it fails with the following exception:

    Started GET "/" for 0:0:0:0:0:0:0:1 at 2017-04-21 12:27:18 +0200
    Processing by ExamplesController#show as DOCX
      Rendered examples/show.docx.caracal (381.4ms)
    Completed 500 Internal Server Error in 418ms (ActiveRecord: 0.0ms)

    ActionView::Template::Error (NAMESPACE_ERR: An attempt is made to create or change an object in a way which is incorrect with regard to namespaces.):
      org.apache.xerces.dom.ElementNSImpl.setName(Unknown Source)
      org.apache.xerces.dom.ElementNSImpl.<init>(Unknown Source)
      org.apache.xerces.dom.CoreDocumentImpl.createElementNS(Unknown Source)
      nokogiri.XmlNode.init(XmlNode.java:340)
      nokogiri.XmlNode.rbNew(XmlNode.java:298)
      nokogiri.XmlNode$INVOKER$s$0$0$rbNew.call(XmlNode$INVOKER$s$0$0$rbNew.gen)
      org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
      ...

After that there are 992 more lines of `org.jruby...` stacktrace. Any idea on how to get it to work? I like and use prawn in my project and caracal seems perfect to generate Word documents.

**Comment by jdugan** [comment] 2017-04-21 13:58
Hi, Jan.

I confess I've never used Caracal with JRuby.  Let me see if I can recreate the issue on my local machine.  FWIW, I assure you the library functions as advertised on every version of MRI I've ever tried.  It's not a terribly sophisticated codebase, especially not ruby-wise.  It's all fairly standard stuff, really.

I'm moving overseas this weekend, so I'll try to look into this today.  But if you don't hear from me again for a few days, I won't have abandoned your concern.  I'll just be jetlagged as shit. :)

**Comment by jandillmann** [comment] 2017-04-21 14:15
Hi John,

thanks for getting back so quickly on this issue. It does work with MRI as far as I can see, but sadly I'm forced to use JRuby for this project.

I was able to debug my way step by step down to [line 19 in `core_renderer.rb`](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/renderers/core_renderer.rb#L19).

    xml.send 'cp:coreProperties', root_options do

From there nokogiri (1.7.1-java) takes over and the exception seems to be raised in [line 89 of xml/document.rb](https://github.com/sparklemotion/nokogiri/blob/master/lib/nokogiri/xml/document.rb#L89).

    elm = Nokogiri::XML::Element.new(name, self, &block)

Good luck with your move overseas, I'm happy to hear back from you.

**Comment by jdugan** [comment] 2017-04-21 15:15
Sure, I get it.  I only mentioned MRI to reassure you that the library is not--like so many gems--an untested pile of garbage. :)

You're gonna love this, but I just installed jruby (9.1.7.0) via RVM on my mac and ran the example project without any issues at all.  I guess it's possible there's some difference between 9.1.7 and 9.1.8 that's causing the issue, but I kind of doubt that.

My initial reading of the error is that the JVM is objecting to the way Caracal creates namespaced nodes via Nokogiri.  I'm wondering if the JVM you're using is stricter about this procedure than the one on my mac.  That might explain why my jruby project seems to think everything is okay and yours is objecting immediately.  I found a few examples of folks asking about this kind of thing (related to completely different languages/libraries--SOAP questions, mostly) on StackOverflow.

I wrote most of these renderer classes a few years ago now, but I believe the way I'm defining the nodes was canonical Nokogiri at the time.  There may be a slightly different syntax we can use to satisfy stricter XML implementations.  In any event, that seems like the most fruitful place to start, based on my limited investigation.  

I'll look around some more later this afternoon, but I thought I'd mention what I found in the event that I don't get much further before I have to start packing, etc.  You strike me as a capable programmer--figured you might be able to make some headway while I'm out of pocket.

**Comment by jandillmann** [comment] 2017-04-23 15:13
Hi John,

I hope you arrived well overseas. I tried several combinations of JRuby (9.1.7.0 and 9.1.8.0 via RVM on macOS) and nokogiri (1.6.7, 1.6.8, 1.7.0, 1.7.1) in separate gemsets with the master branch of caracal-example – but to no avail. The gemfile looks something like this:

    gem 'rails', '~> 4.2.8'
    gem 'activerecord-jdbcsqlite3-adapter'
    gem 'nokogiri', '1.7.0'
    gem 'caracal-rails'

Same error on Windows Server 2012 R2 (where it ultimately has to run) with JRuby installed from their Website. I suspect the issue is more on the nokogiri side than on JRuby's. Which versions were you using that did work?

**Comment by jdugan** [comment] 2017-04-25 12:00
Huh.  I'm using JRuby 9.1.7.0 and Nokogiri 1.7.1 java on OSX and it worked perfectly for me.  I have to think this has something to do with either (a) how Nokogiri is being natively compiled on your machine or (b) some difference in our Java runtime environments.  Here's what I get when I run `java -version`:

```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Either way, the issue seems to be with the way Caracal is creating some of its prefixed/namespaced nodes.  The `xml.send 'prefix:node_name', options &block` syntax seems to be what the runtime interpreter thinks is wonky.  (Hard to disagree, frankly.)  We may be able to circumvent the issue by converting everything to the `xml['prefix'].node_name options, &block` syntax.  

I can't remember why I used the `send`-style syntax in the first place.  I think it resolved some problem Nokogiri had when using namespaces with a block?

**Comment by jandillmann** [comment] 2017-05-24 12:12
Sorry for getting back to you so late, but I couldn't figure out why it's not working on my machine and resorted to creating PDFs with Prawn for now.

If it helps, here is the output of my `java -version`:

    java version "1.8.0_92"
    Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
    Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by jdugan** [comment] 2017-05-24 15:21
Shit.  I hate that this was  your experience with the gem.  I'm running an environment only a few patches behind you, so it's difficult to imagine that's the root cause, but I guess it's possible.  I'll leave the issue open because I think supporting JRuby is an important requirement for the library.  And I'll let you know if I have any updates.

**Comment by henrychung** [comment] 2017-07-18 22:00
I was experiencing the same issues and did a bunch of digging and came up with a lot of useful information. The issues are actually not with java or nokogiri exactly, but rather the xml engine. Where as nokogiri would normally use libxml2, it uses the xerces java parser in jruby. This explains why we only see the issue in jruby.

Apparently, Xerces is "stricter" in some ways, including how one specifies xml namespaces for an element. So `xml.send 'cp:coreProperties'` is fine according to libxml (and to me, too, honestly). In Xerces, it is not permitted. You have to explicitly set the name space and then tag like so `xml['cp'].send 'coreProperties'`.

Changing all of the namspaced tags to follow this pattern worked, and the java exception went away and I got a .docx file!

However, the documents were all blank. So a little more digging turned up something mysterious. Following that pattern, `xml.send 'w:p'` could be rewritten as `xml['w'].send 'p'`. Mysteriously, `.send 'p'` always returns nil. I think there is a monkey patch somewhere that is intercepting the call before builder's `.method_missing`  gets to it. Maybe it's in Rails, maybe it's in Nokogiri. Maybe it's the `puts` alias. I don't know for sure. I didn't have too much time to put in to trace it.

Calling `.method_missing` directly like so: `xml['w'].method_missing 'p'` seems to get around this and I was able to get correctly generated documents.

I tidied up the changes and opted for the normal implicit method_missing invoking approach since we no longer have the colons in the tag names: `xml['cp'].coreProperties` and `xml['w'].p`

I've forked the project and committed my changes:
https://github.com/henrychung/caracal

@jandillmann : I hope this helps you out with your project.

@jdugan : Thanks for all your hard work and time that you put into this project. It is truly the best (the *only*, really!) library out there for generating .docx files! I'll go over my code once more and will create a pull request. I hope my contributions will be useful.

**Comment by jdugan** [comment] 2017-07-18 22:44
Holy shit.  Consider yourself nominated for CNN's Heroes this year.  That is an awesome and amazingly helpful research effort (and not just because it confirmed my suspicion about strictness!).

It killed me that a user couldn't get the library to work with jruby.  Thank you so much for this.  I can't wait to see the PR.

**Comment by jandillmann** [comment] 2017-09-04 13:39
Wow, thanks a lot! Works like a charm for me now.

**Closed** 2017-09-09 07:36 UTC
