### ISSUE TITLE
Customizable Headers and Footers

### ISSUE THREAD

**Issue by fatuhoku** [trade-informatics/caracal#44] opened 2016-06-10 11:15 UTC
It shouldn't be too difficult to allow these to be customized, right?

**Comment by jdugan** [comment] 2016-06-10 13:25
You're certainly welcome to file a pull request.  Please see the [README](https://github.com/trade-informatics/caracal/issues/24) section for more details on how to proceed with feature development.

In the meantime, I'm going to close this for largely being a duplicate of [Issue 24](https://github.com/trade-informatics/caracal/issues/24).

**Closed by jdugan** 2016-06-10 13:25 UTC
